### ISSUE TITLE
Error when runserver

### ISSUE THREAD

**Issue by MichaelHeo** [scailer/django-user-activity-log#4]
Hey!
I followed your README teaching how to use this tool, but when I go "python manage.py runserver", an error occurs.

Could you please help me?

`Unhandled exception in thread started by <function wrapper at 0x7f853a26cc80>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 142, in inner_run
    handler = self.get_handler(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 46, in get_internal_wsgi_application
    return get_wsgi_application()
  File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 153, in __init__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: this constructor takes no arguments`

**Comment by ericbolo** [comment]
I get a similar error (python 3.6):

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f29ff2ab378>
Traceback (most recent call last):
  File "/home/eric/anaconda3/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 147, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 28, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 68, in get_handler
    return get_internal_wsgi_application()
  File "/home/eric/anaconda3/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 47, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/eric/anaconda3/lib/python3.6/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/home/eric/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/eric/batvoice/web/online_callwatch_pvcp/callwatch_pvcp/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/eric/anaconda3/lib/python3.6/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/home/eric/anaconda3/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/home/eric/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters

**Comment by AhmedAlZabidi** [comment]
I got the similar error

**Comment by TerminalFi** [comment]
@AhmedAlZabidi 

See for fixes

```
https://github.com/scailer/django-user-activity-log/pull/5/files
```
